CREATE TABLE [dbo].[Medical0027_PainManagementMod25_AtRiskClaims](
	[AmountAtRisk] [numeric](24, 2) NULL,
	[ClaimSeq] [bigint] NULL,
	[ClaimICN] [varchar](30) NULL,
	[ClaimLineNumber] [int] NULL,
	[ClaimForm] [varchar](10) NULL,
	[ClaimTypeCode] [varchar](10) NULL,
	[ClaimTypeDescription] [varchar](255) NULL,
	[ClaimBillType] [varchar](3) NULL,
	[AmountPaid] [money] NULL,
	[AmountAllowed] [money] NULL,
	[AmountCharged] [money] NULL,
	[AmountMedicare] [money] NULL,
	[AmountInternalCOB] [money] NULL,
	[AmountExternalCOB] [money] NULL,
	[AmountTotCOB] [money] NULL,
	[AmountCopay] [money] NULL,
	[AmountDeductible] [money] NULL,
	[AmountCoinsurance] [money] NULL,
	[AmountOOP] [money] NULL,
	[AmountHSA] [money] NULL,
	[PricingMethodCode] [varchar](10) NULL,
	[PricingMethodDescription] [varchar](255) NULL,
	[SystemPricingMethod] [varchar](50) NULL,
	[FeeScheduleSeq] [int] NULL,
	[PPSSeq] [int] NULL,
	[ReimbursementRate] [float] NULL,
	[ContractID] [varchar](30) NULL,
	[CheckNumber] [varchar](30) NULL,
	[PrimaryExternalPayerID] [varchar](30) NULL,
	[PrimaryExternalPayerName] [varchar](150) NULL,
	[ReceivedDate] [datetime] NULL,
	[AdjudicationDate] [datetime] NULL,
	[PaidDate] [date] NULL,
	[ServiceFromDate] [date] NULL,
	[ServiceToDate] [date] NULL,
	[AdmissionDate] [date] NULL,
	[DischargeDate] [date] NULL,
	[ServiceID] [varchar](255) NULL,
	[ProcedureCode] [varchar](10) NULL,
	[ProcedureDescription] [varchar](255) NULL,
	[ProcedureNumberOfUnits] [int] NULL,
	[ProcedureMod_1] [varchar](2) NULL,
	[ProcedureMod_2] [varchar](2) NULL,
	[ProcedureMod_3] [varchar](2) NULL,
	[ProcedureMod_4] [varchar](2) NULL,
	[RevenueCode] [varchar](10) NULL,
	[RevenueDescription] [varchar](255) NULL,
	[VisitID] [varchar](255) NULL,
	[LevelOfCareCode] [varchar](10) NULL,
	[LevelOfCareDescription] [varchar](255) NULL,
	[SystemLevelOfCare] [varchar](50) NULL,
	[PPSCode] [varchar](10) NULL,
	[PPSDescription] [varchar](255) NULL,
	[PPSCodeType] [varchar](25) NULL,
	[PPSGrouperVersion] [varchar](15) NULL,
	[RelativeWeight] [float] NULL,
	[BaseRate] [money] NULL,
	[AdjustedRate] [money] NULL,
	[ClaimLengthOfStay] [int] NULL,
	[ClaimNumberOfDaysPaid] [int] NULL,
	[ClaimNonCoveredDays] [int] NULL,
	[VisitLengthOfStay] [int] NULL,
	[VisitNumberOfDaysPaid] [int] NULL,
	[VisitNonCoveredDays] [int] NULL,
	[EpisodeOfCare] [varchar](255) NULL,
	[EpisodeStartDate] [date] NULL,
	[EpisodeEndDate] [date] NULL,
	[EpisodeConditionCode] [varchar](10) NULL,
	[EpisodeConditionDescription] [varchar](255) NULL,
	[EpisodeCodeType] [varchar](25) NULL,
	[TypeOfServiceCode] [varchar](10) NULL,
	[TypeOfServiceDescription] [varchar](255) NULL,
	[PlaceOfServiceCode] [varchar](10) NULL,
	[PlaceOfServiceDescription] [varchar](255) NULL,
	[LocationID] [varchar](30) NULL,
	[LocationZipCode] [varchar](10) NULL,
	[MedicalRecordNumber] [varchar](30) NULL,
	[PriorAuthorizationNumber] [varchar](30) NULL,
	[PatientControlNumber] [varchar](25) NULL,
	[AdmissionTypeCode] [varchar](10) NULL,
	[AdmissionTypeDescription] [varchar](255) NULL,
	[AdmissionSourceCode] [varchar](10) NULL,
	[AdmissionSourceDescription] [varchar](255) NULL,
	[DischargeStatusCode] [varchar](10) NULL,
	[DischargeStatusDescription] [varchar](255) NULL,
	[MCOFlag] [char](1) NULL,
	[MCOAnalyticsID] [varchar](30) NULL,
	[MCOName] [varchar](150) NULL,
	[MCORegionCode] [varchar](5) NULL,
	[MCORegionDescription] [varchar](100) NULL,
	[MCOClaimICN] [varchar](30) NULL,
	[MCOClaimLineNumber] [int] NULL,
	[MCOPaidDate] [date] NULL,
	[ACOFlag] [char](1) NULL,
	[ACOAnalyticsID] [varchar](30) NULL,
	[ACOName] [varchar](150) NULL,
	[UncoveredServiceFlag] [char](1) NULL,
	[CrossoverFlag] [char](1) NULL,
	[EmergencyFlag] [char](1) NULL,
	[TraumaFlag] [char](1) NULL,
	[PriorAuthFlag] [char](1) NULL,
	[LockInFlag] [char](1) NULL,
	[LineOfBusiness_Level1Code] [varchar](10) NULL,
	[LineOfBusiness_Level1Description] [varchar](100) NULL,
	[LineOfBusiness_Level2Code] [varchar](10) NULL,
	[LineOfBusiness_Level2Description] [varchar](100) NULL,
	[LineOfBusiness_Level3Code] [varchar](10) NULL,
	[LineOfBusiness_Level3Description] [varchar](100) NULL,
	[LineOfBusiness_Level4Code] [varchar](10) NULL,
	[LineOfBusiness_Level4Description] [varchar](100) NULL,
	[PlanCode] [varchar](10) NULL,
	[PlanDescription] [varchar](255) NULL,
	[ProductCode] [varchar](10) NULL,
	[ProductDescription] [varchar](255) NULL,
	[NetworkTypeCode] [varchar](10) NULL,
	[NetworkTypeDescription] [varchar](255) NULL,
	[SystemNetworkType] [varchar](50) NULL,
	[InNetworkFlag] [char](1) NULL,
	[SystemRuleset] [varchar](50) NULL,
	[DiagnosisCodeType] [varchar](10) NULL,
	[PrimaryDiagnosisCode] [varchar](10) NULL,
	[PrimaryDiagnosisDescription] [varchar](255) NULL,
	[SecondaryDiagnosisCode] [varchar](10) NULL,
	[SecondaryDiagnosisDescription] [varchar](255) NULL,
	[RenderingProviderAnalyticsID] [varchar](25) NULL,
	[RenderingProviderAnalyticsIDType] [varchar](20) NULL,
	[RenderingProviderAnalyticsPeerGroup] [varchar](255) NULL,
	[RenderingProviderAnalyticsPeerGroupType] [varchar](50) NULL,
	[RenderingProviderID] [varchar](25) NULL,
	[RenderingProviderNPI] [varchar](10) NULL,
	[RenderingProviderName] [varchar](300) NULL,
	[RenderingProviderTaxonomyCode] [varchar](10) NULL,
	[RenderingProviderTaxonomyGroup] [varchar](100) NULL,
	[RenderingProviderTaxonomyClass] [varchar](150) NULL,
	[RenderingProviderTaxonomySpecialty] [varchar](150) NULL,
	[RenderingProviderTypeCode] [varchar](5) NULL,
	[RenderingProviderTypeDescription] [varchar](255) NULL,
	[RenderingProviderSpecialtyCode] [varchar](5) NULL,
	[RenderingProviderSpecialtyDescription] [varchar](255) NULL,
	[BillingProviderAnalyticsID] [varchar](25) NULL,
	[BillingProviderAnalyticsIDType] [varchar](20) NULL,
	[BillingProviderAnalyticsPeerGroup] [varchar](255) NULL,
	[BillingProviderAnalyticsPeerGroupType] [varchar](50) NULL,
	[BillingProviderID] [varchar](25) NULL,
	[BillingProviderNPI] [varchar](10) NULL,
	[BillingProviderCCN] [varchar](6) NULL,
	[BillingProviderName] [varchar](300) NULL,
	[BillingProviderTaxonomyCode] [varchar](10) NULL,
	[BillingProviderTaxonomyGroup] [varchar](100) NULL,
	[BillingProviderTaxonomyClass] [varchar](150) NULL,
	[BillingProviderTaxonomySpecialty] [varchar](150) NULL,
	[BillingProviderTypeCode] [varchar](5) NULL,
	[BillingProviderTypeDescription] [varchar](255) NULL,
	[BillingProviderSpecialtyCode] [varchar](5) NULL,
	[BillingProviderSpecialtyDescription] [varchar](255) NULL,
	[BillingProviderAddressFirstLine] [varchar](255) NULL,
	[BillingProviderAddressSecondLine] [varchar](255) NULL,
	[BillingProviderCity] [varchar](255) NULL,
	[BillingProviderState] [varchar](2) NULL,
	[BillingProviderZipCode] [varchar](10) NULL,
	[BillingProviderTIN] [varchar](15) NULL,
	[BillingProviderEmail] [varchar](255) NULL,
	[BillingProviderFax] [varchar](50) NULL,
	[AttendingProviderAnalyticsID] [varchar](25) NULL,
	[AttendingProviderAnalyticsIDType] [varchar](20) NULL,
	[AttendingProviderAnalyticsPeerGroup] [varchar](255) NULL,
	[AttendingProviderAnalyticsPeerGroupType] [varchar](50) NULL,
	[AttendingProviderID] [varchar](25) NULL,
	[AttendingProviderNPI] [varchar](10) NULL,
	[AttendingProviderName] [varchar](300) NULL,
	[AttendingProviderTaxonomyCode] [varchar](10) NULL,
	[AttendingProviderTypeCode] [varchar](5) NULL,
	[AttendingProviderTypeDescription] [varchar](255) NULL,
	[AttendingProviderSpecialtyCode] [varchar](5) NULL,
	[AttendingProviderSpecialtyDescription] [varchar](255) NULL,
	[ReferringProviderAnalyticsID] [varchar](25) NULL,
	[ReferringProviderAnalyticsIDType] [varchar](20) NULL,
	[ReferringProviderAnalyticsPeerGroup] [varchar](255) NULL,
	[ReferringProviderAnalyticsPeerGroupType] [varchar](50) NULL,
	[ReferringProviderID] [varchar](25) NULL,
	[ReferringProviderNPI] [varchar](10) NULL,
	[ReferringProviderName] [varchar](300) NULL,
	[ReferringProviderTaxonomyCode] [varchar](10) NULL,
	[ReferringProviderTypeCode] [varchar](5) NULL,
	[ReferringProviderTypeDescription] [varchar](255) NULL,
	[ReferringProviderSpecialtyCode] [varchar](5) NULL,
	[ReferringProviderSpecialtyDescription] [varchar](255) NULL,
	[ReferringProviderZipCode] [varchar](10) NULL,
	[MemberDistanceToReferringProvider] [numeric](18, 2) NULL,
	[MemberAnalyticsID] [varchar](30) NULL,
	[MemberAnalyticsIDType] [varchar](20) NULL,
	[MemberMonthID] [int] NULL,
	[SubscriberID] [varchar](30) NULL,
	[PersonID] [varchar](10) NULL,
	[CardholderID] [varchar](30) NULL,
	[MemberID] [varchar](30) NULL,
	[MemberMedicaidID] [varchar](30) NULL,
	[MemberMedicareID] [varchar](30) NULL,
	[MemberName] [varchar](300) NULL,
	[MemberFirstName] [varchar](100) NULL,
	[MemberLastName] [varchar](100) NULL,
	[MemberAge] [int] NULL,
	[MemberGender] [varchar](10) NULL,
	[MemberRelationshipCode] [varchar](10) NULL,
	[MemberRelationshipDescription] [varchar](100) NULL,
	[MemberDOB] [date] NULL,
	[MemberDOD] [date] NULL,
	[MemberAddressFirstLine] [varchar](255) NULL,
	[MemberAddressSecondLine] [varchar](255) NULL,
	[MemberCity] [varchar](255) NULL,
	[MemberState] [varchar](2) NULL,
	[MemberZipCode] [varchar](10) NULL,
	[MemberCountyCode] [varchar](10) NULL,
	[MemberCountyDescription] [varchar](255) NULL,
	[MemberPhone] [varchar](50) NULL,
	[MemberEmail] [varchar](255) NULL,
	[MemberEmployerID] [varchar](30) NULL,
	[MemberEmployerName] [varchar](100) NULL,
	[MemberGroupID] [varchar](30) NULL,
	[MemberGroupName] [varchar](100) NULL,
	[MemberSubGroupID] [varchar](30) NULL,
	[MemberSubGroupName] [varchar](100) NULL,
	[MemberClassID] [varchar](30) NULL,
	[MemberClassName] [varchar](100) NULL,
	[MemberAidCategoryCode] [varchar](10) NULL,
	[MemberAidCategoryDescription] [varchar](255) NULL,
	[MemberEligibilityCategoryCode] [varchar](10) NULL,
	[MemberEligibilityCategoryDescription] [varchar](255) NULL,
	[MemberPCPAnalyticsID] [varchar](25) NULL,
	[MemberPCPName] [varchar](300) NULL,
	[MemberHealthRiskFlag] [char](1) NULL,
	[YearOfService] [int] NULL,
	[YearQuarter] [varchar](7) NULL,
	[YearMonth] [varchar](7) NULL,
	[location_address] [varchar](max) NULL,
	[location_latitude] [float] NULL,
	[location_longitude] [float] NULL,
	[member_address] [varchar](max) NULL,
	[member_latitude] [float] NULL,
	[member_longitude] [float] NULL,
	[sec_organization_id] [nvarchar](64) NOT NULL,
	[sec_tenant_id] [nvarchar](36) NOT NULL,
	[AliviaBenefitLine] [varchar](255) NULL,
	[AliviaModelID] [varchar](255) NULL,
	[AliviaModelName] [varchar](255) NULL,
	[at_ai_sched_proc_exec_id] [varchar](255) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Medical0027_PainManagementMod25_BillProvMetrics]    Script Date: 7/29/2021 7:46:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Medical0027_PainManagementMod25_BillProvMetrics](
	[BillingProviderAnalyticsID] [varchar](25) NULL,
	[BillingProviderName] [varchar](300) NULL,
	[BillingProviderAnalyticsPeerGroup] [varchar](255) NULL,
	[AmountAtRisk] [money] NULL,
	[AmountAtRiskMCO] [money] NULL,
	[AmountAtRiskFFS] [money] NULL,
	[NumberProcedures] [int] NULL,
	[NumberMembers] [int] NULL,
	[NumberClaimsAtRisk] [int] NULL,
	[AverageNumberClaimsAtRiskPerMember] [numeric](24, 2) NULL,
	[ProportionClaimsAtRisk] [numeric](24, 2) NULL,
	[sec_organization_id] [nvarchar](64) NOT NULL,
	[sec_tenant_id] [nvarchar](36) NOT NULL,
	[at_ai_sched_proc_exec_id] [varchar](255) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Medical0027_PainManagementMod25_BillProvRiskScores]    Script Date: 7/29/2021 7:46:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Medical0027_PainManagementMod25_BillProvRiskScores](
	[BillingProviderAnalyticsID] [varchar](255) NULL,
	[BillingProviderName] [varchar](255) NULL,
	[BillingProviderAnalyticsPeerGroup] [varchar](255) NULL,
	[AmountAtRisk] [float] NULL,
	[AmountAtRiskMCO] [float] NULL,
	[AmountAtRiskFFS] [float] NULL,
	[NumberProcedures] [int] NULL,
	[NumberMembers] [int] NULL,
	[NumberClaimsAtRisk] [int] NULL,
	[AverageNumberClaimsAtRiskPerMember] [float] NULL,
	[ProportionClaimsAtRisk] [float] NULL,
	[sec_organization_id] [nvarchar](255) NOT NULL,
	[sec_tenant_id] [nvarchar](255) NOT NULL,
	[at_ai_sched_proc_exec_id] [varchar](255) NULL,
	[OutlierFlag] [float] NULL,
	[RiskScore] [float] NULL,
	[RelativeRiskPercentile] [float] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Medical0027_PainManagementMod25_RendProvMetrics]    Script Date: 7/29/2021 7:46:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Medical0027_PainManagementMod25_RendProvMetrics](
	[RenderingProviderAnalyticsID] [varchar](25) NULL,
	[RenderingProviderName] [varchar](300) NULL,
	[RenderingProviderAnalyticsPeerGroup] [varchar](255) NULL,
	[AmountAtRisk] [money] NULL,
	[AmountAtRiskMCO] [money] NULL,
	[AmountAtRiskFFS] [money] NULL,
	[NumberProcedures] [int] NULL,
	[NumberMembers] [int] NULL,
	[NumberClaimsAtRisk] [int] NULL,
	[AverageNumberClaimsAtRiskPerMember] [numeric](24, 2) NULL,
	[ProportionClaimsAtRisk] [numeric](24, 2) NULL,
	[sec_organization_id] [nvarchar](64) NOT NULL,
	[sec_tenant_id] [nvarchar](36) NOT NULL,
	[at_ai_sched_proc_exec_id] [varchar](255) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Medical0027_PainManagementMod25_RendProvRiskScores]    Script Date: 7/29/2021 7:46:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Medical0027_PainManagementMod25_RendProvRiskScores](
	[RenderingProviderAnalyticsID] [varchar](255) NULL,
	[RenderingProviderName] [varchar](255) NULL,
	[RenderingProviderAnalyticsPeerGroup] [varchar](255) NULL,
	[AmountAtRisk] [float] NULL,
	[AmountAtRiskMCO] [float] NULL,
	[AmountAtRiskFFS] [float] NULL,
	[NumberProcedures] [int] NULL,
	[NumberMembers] [int] NULL,
	[NumberClaimsAtRisk] [int] NULL,
	[AverageNumberClaimsAtRiskPerMember] [float] NULL,
	[ProportionClaimsAtRisk] [float] NULL,
	[sec_organization_id] [nvarchar](255) NOT NULL,
	[sec_tenant_id] [nvarchar](255) NOT NULL,
	[at_ai_sched_proc_exec_id] [varchar](255) NULL,
	[OutlierFlag] [float] NULL,
	[RiskScore] [float] NULL,
	[RelativeRiskPercentile] [float] NULL
) ON [PRIMARY]
GO
